### ISSUE TITLE
No completions for dependencies

### ISSUE THREAD

**Issue by krgn** [jyp/dante#53] opened 2017-12-02 13:24 UTC
Hi,

I have a problem getting company completions working for packages other than `base`.  I'm working on a small nix-based example, with `shell.nix`, `default.nix` and a `.dir-locals.el` site which sets `dante-project-root` to the project directory. 

My cabal file looks like this:

```
name:                hs
version:             0.1.0.0
-- synopsis:            
-- description:         
license:             BSD3
license-file:        LICENSE
author:              Karsten Gebbert
maintainer:          k@ioctl.it
-- copyright:           
-- category:            
build-type:          Simple
extra-source-files:  ChangeLog.md
cabal-version:       >=1.10

executable hs
  main-is:             Main.hs
  -- other-modules:       
  -- other-extensions:    
  build-depends:       base >=4.1 && <4.20
                       ,aeson 
                       ,bytestring
                       ,text
                       ,binary
  -- hs-source-dirs:      
  default-language:    Haskell2010
```

and the corresponding generated (cabal2nix) derivation:

```
{ mkDerivation, aeson, base, binary, bytestring, stdenv, text }:
mkDerivation {
  pname = "hs";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [ aeson base binary bytestring text ];
  license = stdenv.lib.licenses.bsd3;
}
```

The project builds fine both, using nix and cabal in a nix-shell, and when I run `nix-shell --run "cabal repl"` it allows me to import e.g. `Data.Binary.Get`. So everything works as expected. However, when I try to complete a symbol like `get<tab>` using company, it only offers `getChar`, `getContents` and `getLine`, but not `getWord8`.

I set up dante itself exactly as per instructions in the README.

Is there anything obvious I might have overlooked that could lead to this problem?

Thank you for any hints, and for this otherwise great mode/code!

k

ps: I should add I'm using ` dante  Version: 20171201.523`

**Comment by jyp** [comment] 2017-12-03 19:37
Thanks for the detailed bug report. However I am pretty sure what the problem is (documented in #54) so I'm closing this one as it lacks insight in what's going on. Also, please see if the workaround proposed in #54 works for you, and and continue the conversation there.

**Closed by jyp** 2017-12-03 19:37 UTC
