### ISSUE TITLE
ParseError due to default-extensions not being considered.

### ISSUE THREAD

**Issue by ar1a** [jyp/dante#113] opened 2019-04-12 03:19 UTC
In a simple project (https://github.com/ar1a/hsauth/tree/3a7e7a033f4e9cb126195f6700b4cb1333524ea1). QuasiQuotes is on in the .cabal default-extensions, yet inside Auth.hs there is a parse error after it's used (`[re|.@.|]`). I solved this by adding the explicit language extension to the top, but that's just a hack.

**Comment by sboosali** [comment] 2019-04-12 03:27
what are the values of `dante-command-line`, `dante-target`,
`dante-project-root`?

**Comment by ar1a** [comment] 2019-04-12 04:59
`dante-command-line` is nil

`dante-target` is nil

and `dante-project-root` is `"~/projects/hsauth2/"`

**Comment by jyp** [comment] 2019-04-12 13:28
You can call `M-x dante-diagnose` to see how GHCi was called. (Or just read the *messages* buffer). Check if that looks correct.

**Comment by jyp** [comment] 2019-08-01 18:52
Unlikely that the issue is with dante (the burden of configuring ghci falls to the user). Closing.

**Closed by jyp** 2019-08-01 18:52 UTC
