### ISSUE TITLE
company-mode breaks dante

### ISSUE THREAD

**Issue by ElvishJerricco** [jyp/dante#50] opened 2017-11-02 20:48 UTC
When I add `company-mode` to `dante-mode-hook`, starting dante yields this error:

```
found nil end 388 start 357 id-start 47
```

And then dante gets stuck in a `busy` state. If I don't add it as a hook and manually run `company-mode` after `dante-mode`, it works for one completion before breaking in the same way.

Sorry, I'm quite useless with Emacs lisp, so I don't have the first idea of how to debug this.

**Comment by ElvishJerricco** [comment] 2017-11-02 20:53
Actually, it seems this error is partially due to the GHCi process not be started automatically? If I do something like `dante-info` to force it to start, everything continues working. But afterwards, if I enable flycheck, it breaks. So this might be related to #48.

**Comment by ElvishJerricco** [comment] 2017-11-02 20:57
One more note: In the state I had it working (getting GHCi started manually, but not starting flycheck), making edits that result in parse errors yields large volumes of messages like the above, though completion continues to work nonetheless.

**Comment by jyp** [comment] 2017-11-18 18:21
What versions are you using? I believe that I fixed this in 202ae44286d3640bd68116ce20a7fcb498618087

**Comment by jyp** [comment] 2017-11-20 08:12
Duplicate of #48

**Closed by jyp** 2017-11-20 08:12 UTC
